<a href="https://colab.research.google.com/github/PSKKarthik/DWDM-EXP-1/blob/main/DWDMexp_1_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
data=[1,2,3]
print(data)

[1, 2, 3]


In [ ]:
data=[[1,2,3],[5,6,8]]
data[:][1]

[5, 6, 8]

In [ ]:
data1=[[1,2,3],[4,5,6]]
arr=np.array(data1)
arr[:,1]

array([2, 5])

In [ ]:
import numpy as np
data=[[1,2,3],[4,5,6],[7,8,9]]
arr=np.array(data)
arr[:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
import numpy as np
import numpy as np
data=[[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]]
arr=np.array(data)
arr.T

array([[[1, 1],
        [4, 4],
        [7, 7]],

       [[2, 2],
        [5, 5],
        [8, 8]],

       [[3, 3],
        [6, 6],
        [9, 9]]])

In [ ]:
import numpy as np
import numpy as np
data=[[[1,2,3],[4,5,6],[7,8,9]],[[11,22,33],[43,50,16],[71,83,91]]]
arr=np.array(data)
arr.swapaxes(0,1)

array([[[ 1,  2,  3],
        [11, 22, 33]],

       [[ 4,  5,  6],
        [43, 50, 16]],

       [[ 7,  8,  9],
        [71, 83, 91]]])

In [ ]:
data1=[[1,2,3],[4,5,6],[7,8,9]]
arr=np.array(data1)
arr2=arr.T
print(arr)
print("\n")
print(arr2)
print("\n")
print(arr2[-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1 4 7]
 [2 5 8]
 [3 6 9]]


[3 6 9]


In [ ]:
import numpy as np

data=[[[1,2,3],[4,5,6],[7,8,9]],[[11,22,33],[43,50,16],[71,83,91]]]
arr=np.array(data)
print(arr)
print("\n")
print(arr[1][:2,:2])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 22 33]
  [43 50 16]
  [71 83 91]]]


[[11 22]
 [43 50]]
